### ISSUE TITLE
`before_validation` instead of `before_create`

### ISSUE THREAD

**Issue by tenshiAMD** [felipediesel/auto_increment#12]
https://github.com/felipediesel/auto_increment/blob/master/lib/auto_increment/active_record.rb#L9

I'm having errors on fields with `presence: true` validation, I purposely not adding the field thus will be always be blank and validation error `can't be blank` always occurs; it suppose `auto_increment` will be able add to the value into it. I disabled the fields `presence: true` just to make it work. Any workarounds for this? or replace the `before_create` and `before_validation`?

I think that `before_validation` callback will be better than the `before_create` to passed all necessary validations. 

What do you think, @felipediesel?

**Comment by felipediesel** [comment]
Don't you think the validation is unnecessary once auto_increment will set this field?

**Comment by tenshiAMD** [comment]
I think its a best practice to always add the validation to those fields that are defined with`null: false` in the database with `presence: true` validation thus error in database and rails will be handled properly.

**Comment by felipediesel** [comment]
Better safe then sorry, right? 

We could add an option to set when it should happen, something like `auto_increment :code, before: :create`, supporting and relying on any ActiveRecord callback.

The problem is that it could also be executed on update, opening a possibility to make mistakes.

From this solution, we could leave it as is and let the programmer handle it (if force is false there is no problem) or we could enforce that it only executes on creation and not in update.

**Comment by tenshiAMD** [comment]
Yeah, I think it could be that way; adding an option like that and making it slightly flexible depending on the usage of it. 👍

**Comment by felipediesel** [comment]
@tenshiAMD Hey! Just published a new version with `before` option.

**Comment by tenshiAMD** [comment]
@felipediesel Thanks!  🎉 👍
