### ISSUE TITLE
Deprecate :scope in favor of :model_scope

### ISSUE THREAD

**Issue by felipediesel** [felipediesel/auto_increment#23]
`:model_scope` is more flexible than `:scope`, therefore I'm planning to deprecate the latter.

**Comment by bksuperking** [comment]
This makes sense. Rather than having code in 2 separate places and having to work out what both scopes options do, just have the `:model_scope` option. 

Also `:scope` could be confusing as it is already a keyword in active record models, and to be honest you would most likely already have an ActiveRecord scope for what you wanted.

**Comment by felipediesel** [comment]
This code won't work as you intended. Additionally please ensure that the tests are updated accordingly.

**Comment by bksuperking** [comment]
Would be a good idea to update the readme also.

**Comment by GuillaumeM59** [comment]
limiting scopes to only model_scopes is loosing ability to scope by new record values (scope by same columns values than new record).

model_scopes limit to class_methods scopes...

```ruby
def build_scopes(query)
  @options[:scope].each do |scope|
    if scope.present? && @record.respond_to?(scope)
      query = query.where(scope => @record.send(scope))
    end
  end

  query
end

def build_model_scope(query)
  @options[:model_scope].reject(&:nil?).each do |scope|
    query = query.send(scope)
  end

  query
end
```

**Comment by felipediesel** [comment]
I’ll keep both.
